### ISSUE TITLE
Details of getting facebook login to work 

### ISSUE THREAD

**Issue by punkouter2021** [Unity3dAzure/AppServicesDemo#19]
So I created an app on facebook.

Copied the key and pasted that in the code.

Turned on authentication for facebook in the Mobile App and checked everything 

Ran the code. Clicked Login. And I get

![image](https://cloud.githubusercontent.com/assets/2973092/14572952/daba6bea-031f-11e6-9429-3197e674b598.png)

**Comment by punkouter2021** [comment]
I fixed it partly.. Didn't completely save the authentication piece before. So I login and I do not see errors but nothing happens.. and the breakpoint at OnLoginComplete is never reached

![image](https://cloud.githubusercontent.com/assets/2973092/14573359/9d5ca468-0322-11e6-9956-1a441e6ed1d0.png)

**Comment by punkouter2021** [comment]
oh. soon as I saved that it just hit the breakpoint..

**Comment by punkouter2021** [comment]
Also can't find hello api on the callback... Well atleast the CRUD on the highscores table works..

**Comment by deadlyfingers** [comment]
@punkouter 
1. I see you are using 'http://' -> I recommend you use 'https://' instead for mobile app services. But not sure if the auth errors are because of just that? 
2. Also this Unity 'referenced script' is missing error is annoying. I get this too and have added this as issue #15. Remove the broken script from the GameObject and try to reattach script to repair the link.
3. You also need to add Facebook App ID and Secret to your Azure App Service Facebook Authentication settings. Also check the following settings are configured in your Facebook app. 
   <img width="386" alt="facebookappdomains" src="https://cloud.githubusercontent.com/assets/1880480/14618835/8fb3c260-05ac-11e6-8a7c-067169163ae3.png">
   <img width="407" alt="facebookappsecurecanvasurl" src="https://cloud.githubusercontent.com/assets/1880480/14618857/a6e6935e-05ac-11e6-80fb-c62052b3ea77.png">
   <img width="776" alt="facebookappadvancedsettings" src="https://cloud.githubusercontent.com/assets/1880480/14618874/b45d72c8-05ac-11e6-9cc0-bc8a14234aa7.png">
   If in doubt where to set this info check out full documentation if need be - https://azure.microsoft.com/en-gb/documentation/articles/app-service-mobile-how-to-configure-facebook-authentication/

Let me know what, if any of those pointers fix the issues you encountered. But I reckon 'https://' will be needed for Facebook auth as I remember having problems myself with 'http://'

**Comment by punkouter2021** [comment]
App ID AND Secret? I thought it was only one... Ill look at it again ..

**Comment by deadlyfingers** [comment]
@punkouter will be closing this issue as I have added developer guide link to readme.
http://www.deadlyfingers.net/azure/azure-app-services-for-unity3d/

Please reopen if this is still an issue.
