### ISSUE TITLE
(Sort of off topic) How you dealing with REST Services / JSON  ?

### ISSUE THREAD

**Issue by punkouter2021** [Unity3dAzure/AppServicesDemo#20]
The Azure part here is 50% of what I am trying to do. Accessing REST APIs is the other part.

Are you using just the WWW class and some JSON library?  I have not been able to find much to get me going in the right direction

**Comment by deadlyfingers** [comment]
The [Mobile Service client](https://github.com/Unity3dAzure/MobileServicesDemo/blob/master/Assets/MobileServices/client/MobileServiceClient.cs) implements [UnityRestClient](https://github.com/ProjectStratus/UnityRestClient) library which uses [JsonFx plugin](https://bitbucket.org/TowerOfBricks/jsonfx-for-unity3d-git/) to parse JSON data. (The reason why JsonFx plugin is because it runs on all mobile platforms, and its also [free](https://bitbucket.org/TowerOfBricks/jsonfx-for-unity3d-git/src/e791b4841384de42ddc98471f7017beec794d140/JsonFx/JsonFx.Json/License.txt?at=master&fileviewer=file-view-default).)

More info about the Mobile / App Service REST APIs supported are on the [MobileService](https://github.com/Unity3dAzure/MobileServices) repro.

**Comment by punkouter2021** [comment]
What do you do when you want to use a public REST service. My guess is something like.
1. Get the REST URLs you need. Call them using the WWW class
2. Take the XML/JSON results and use a XML->Classes converter so you can use objects
3. Use a JSON/Xml Serializer to send XML/Json into those classes 

Am I right? OR missing anything ?

**Comment by deadlyfingers** [comment]
Yes, except I use [RestRequest](https://github.com/ProjectStratus/UnityRestClient/blob/master/Source/RestRequest.cs) instead of Unity WWW class. This might be something to look at again. But the UnityRestClient library has an [XML](https://github.com/ProjectStratus/UnityRestClient/blob/master/Source/Serializers/XmlSerializer.cs) and [JSON](https://github.com/ProjectStratus/UnityRestClient/blob/master/Source/Serializers/JsonSerializer.cs) serializer which uses the JsonFx plugin.

**Comment by punkouter2021** [comment]
Ok. So this is what you do internally to call the Mobile Services is REST calls ? So if I wanted to know how to do REST calls I should look at that ? Between being able to call REST and put into objects + use Azure Mobiles Services that should cover everything I need

**Comment by deadlyfingers** [comment]
@punkouter There are some interesting developments on the [Unity Roadmap](https://unity3d.com/unity/roadmap) for REST and JSON (but I need to read through all the docs to see if I can use it for this project)
- [Unity Web Request](http://docs.unity3d.com/Manual/UnityWebRequest.html)
- [Json Utility](http://docs.unity3d.com/ScriptReference/JsonUtility.html)

But as these are new Unity features and this demo project currently uses UnityRestClient & JsonFx plugin as mentioned. So in this case the REST -> JSON -> Object flow is:
1. [Perform a request on the table](https://github.com/Unity3dAzure/AppServicesDemo/blob/master/Assets/Scripts/AppServicesDemo.cs#L273)
2. [Once response arrives the callback is fired](https://github.com/Unity3dAzure/AppServicesDemo/blob/master/Assets/MobileServices/table/MobileServiceTable.cs#L44)
3. The [table data is returned as JSON data and converted to a list of objects](https://github.com/Unity3dAzure/AppServicesDemo/blob/master/Assets/Scripts/AppServicesDemo.cs#L281) using a [Model object](https://github.com/Unity3dAzure/AppServicesDemo/blob/master/Assets/Scripts/DataModel/Highscore.cs#L5)

**Comment by punkouter2021** [comment]
I wonder if it will get to the point no wrapper is needed ? 

I do have this working for a simple highscore table. My confusion is more about how to use this with an API app instead of a Mobile App.. A API App that uses code first is what I hope to understand at some point. I don't want any javascript anywhere.

Also if my API app uses swagger then it would be nice if I could generate the client proxy so I don't even have to parse json

**Comment by deadlyfingers** [comment]
Good idea - be good to add other features of App Services like API Apps. But I really want to finish the feature set available for Mobile Apps (successor to Mobile Services) first. I've just added a wiki page on current features / possible features to be supported - 
https://github.com/Unity3dAzure/AppServicesDemo/wiki/Azure-App-Service-features-supported-for-Unity3d

**Comment by deadlyfingers** [comment]
Closing this issue for now - Unity Web Request and Json Utility developments are assigned to issue #22
